version: '3'

services:
  app:
    image: kennylajara/job-skills-analyzer-ui:0.2
    build:
      context: .
      dockerfile: Dockerfile
      target: prod

networks:
  default:
    name: nginxproxymanager_default
    external: true
